name: lasuite-keycloak

networks:
  keycloak:
    external: true
  traefik:
    external: true
  meet:
    external: true

services:
  kc_postgresql:
    image: postgres:16
    networks:
      keycloak:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 2s
      retries: 300
    env_file:
    - env.d/kc_postgresql
    volumes:
    - ./data/keycloak:/var/lib/postgresql/data/pgdata

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    networks:
      meet:
      keycloak:
      traefik:
    command: ["start"]
    env_file:
    - env.d/kc_postgresql
    - env.d/keycloak
    depends_on:
      kc_postgresql:
        condition: service_healthy
        restart: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.keycloak.rule=Host(`${KEYLOAK_HOST}`)'
      - 'traefik.http.routers.keycloak.entryPoints=https'
      - 'traefik.http.routers.keycloak.tls=true'
      - 'traefik.http.routers.keycloak.tls.certresolver=le'
      - "traefik.http.routers.keycloak.service=keycloak-entrypoint"
      - 'traefik.http.services.keycloak-entrypoint.loadbalancer.server.port=8080'
